#!/usr/bin/python
# -*- coding: utf-8 -*-

import getopt
import sys
import os
import traceback
import copy
import logging

import collector
import analyzer
import stats_buffer
import util_cli as util

import node_map

log = logging.getLogger('cbhealthchecker')
log.setLevel(logging.INFO)
log.addHandler(logging.StreamHandler())

def parse_opt():
    (bucket, cluster, user, password, txtfile, htmlfile, verbose, inputfile) = ('all', '', '', '', 'clusterstats.txt', 'health_report.html', False, '')

    try:
        (opts, _args) = getopt.getopt(sys.argv[1:], 
                                      'b:c:dh?vp:u:o:i:', [
                'bucket=',
                'cluster=',
                'debug',
                'help',
                'verbose',
                'password=',
                'user=',
                'html=',
                'input=',
                ])
    except getopt.GetoptError, err:
        usage(err)

    for (opt, arg) in opts:
        if opt in ('-h', '-?', '--help'):
            usage()
            sys.exit(0)
        if opt in ('-b', '--bucket'):
            bucket = arg
        if opt in ('-c', '--cluster'):
            cluster = arg
        if opt in ('-u', '--user'):
            user = arg
        if opt in ('-p', '--password'):
            password = arg
        if opt in ('-d', '--debug'):
            log.setLevel(logging.DEBUG)
        if opt in ('-o', '--output'):
            htmlfile = arg
        if opt in ('-v', '--verbose'):
            verbose = True
        if opt in ('-i', '--input'):
            inputfile = arg

    if not cluster and not inputfile: 
        usage()
    return (bucket, cluster, user, password, txtfile, htmlfile, verbose, inputfile, opts)

def usage(error_msg=''):
    if error_msg:
        print "ERROR: %s" % error_msg
        sys.exit(2)

    print """cbhealthchecker - cluster key performance indicator stats

usage: cbhealthchecker CLUSTER USERNAME PASSWORD OPTIONS

CLUSTER:
  --cluster=HOST[:PORT] or -c HOST[:PORT] Default port is 8091
USERNAME:

  -u USERNAME, --user=USERNAME       admin username of the cluster
PASSWORD:
  -p PASSWORD, --password=PASSWORD   admin password of the cluster
OPTIONS:
  -b BUCKETNAME, --bucket=BUCKETNAME Specific bucket name. Default is all buckets
  -i FILENAME, --input=FILENAME      Construct report out of input JSON file
  -o FILENAME, --output=FILENAME     Default output filename is 'health_report.html'
  -d --debug
  -h --help                          Show this help message and exit
  -v --verbose                       Display detailed node level information
"""
    sys.exit(2)

def main():
    (bucket, cluster, user, password, txtfile, htmlfile, verbose, inputfile, opts) = parse_opt()
    #make snapshot for the current cluster status
    retriever = collector.StatsCollector(log)
    retriever.collect_data(bucket, cluster, user, password, inputfile, opts)

    #analyze the snapshot and historic data
    performer = analyzer.StatsAnalyzer(log)
    performer.run_analysis()
    performer.run_report(txtfile, htmlfile, verbose)

if __name__ == '__main__':
    main()
